'use client';

import { useEffect, useState, RefObject } from 'react';

interface Vector2D {
  dx: number;
  dy: number;
}

export interface FlowField {
  width: number;
  height: number;
  cellSize: number;
  getForce: (x: number, y: number) => Vector2D;
}

/**
 * Computes a low-res spatial flow field (distance field gradient) around text elements.
 * Returns a lookup function to get the "escape vector" for any screen coordinate.
 * Particles use this vector to flow around the text instead of intersecting it.
 */
export function useTextFlowField(textRef: RefObject<HTMLElement | null>, cellSize = 12): FlowField | null {
  const [flowField, setFlowField] = useState<FlowField | null>(null);

  useEffect(() => {
    let timeoutId: number;

    const generate = () => {
      const el = textRef.current;
      if (!el) return;

      // Skip flow field on mobile — BFS is CPU-heavy and text collision
      // is a desktop-only visual refinement
      if (window.innerWidth < 768) return;

      const w = window.innerWidth;
      const h = window.innerHeight;
      
      const canvas = document.createElement('canvas');
      canvas.width = w;
      canvas.height = h;
      const ctx = canvas.getContext('2d', { willReadFrequently: true });
      if (!ctx) return;
      
      // Find all single-character spans generated by SplitText
      // or any direct text nodes if SplitText isn't used
      const spans = Array.from(el.querySelectorAll('span')).filter(
        span => span.textContent && span.textContent.trim().length === 1
      );

      if (spans.length === 0) return; // not ready

      // Draw each character into the offscreen canvas at its exact DOM position
      ctx.fillStyle = 'white';
      ctx.textBaseline = 'top';
      ctx.textAlign = 'left';

      spans.forEach((charEl) => {
        const text = charEl.textContent!.trim();
        const rect = charEl.getBoundingClientRect();
        const style = window.getComputedStyle(charEl);
        
        ctx.font = `${style.fontWeight} ${style.fontSize} ${style.fontFamily}`;
        
        // Minor adjust for baseline vs bounding box differences across fonts
        // Using top baseline, the text usually draws slightly below the exact CSS rect top,
        // but for a 12px grid collision map, it is perfectly accurate enough.
        ctx.fillText(text, rect.left, rect.top);
      });

      const cols = Math.ceil(w / cellSize);
      const rows = Math.ceil(h / cellSize);
      const grid = new Float32Array(cols * rows * 2); // dx, dy pairs
      
      const imgData = ctx.getImageData(0, 0, w, h).data;
      const isText = new Uint8Array(cols * rows);
      
      // 1. Mark text cells
      for (let y = 0; y < rows; y++) {
        for (let x = 0; x < cols; x++) {
          const px = Math.floor(x * cellSize + cellSize / 2);
          const py = Math.floor(y * cellSize + cellSize / 2);
          if (px < w && py < h) {
            const idx = (py * w + px) * 4;
            if (imgData[idx + 3] > 64) {
              isText[y * cols + x] = 1;
            }
          }
        }
      }

      // 2. Compute Distance Field using Multi-Source BFS
      const dist = new Float32Array(cols * rows);
      dist.fill(999999);
      const queue: number[] = [];
      
      // Enqueue all EMPTY cells as distance 0
      for (let i = 0; i < cols * rows; i++) {
        if (isText[i] === 0) {
          dist[i] = 0;
          queue.push(i);
        }
      }
      
      // 8-way directions
      const dirs = [
        [-1, 0, 1], [1, 0, 1], [0, -1, 1], [0, 1, 1],
        [-1, -1, 1.414], [1, -1, 1.414], [-1, 1, 1.414], [1, 1, 1.414]
      ];
      
      let head = 0;
      while (head < queue.length) {
        const curr = queue[head++];
        const cx = curr % cols;
        const cy = Math.floor(curr / cols);
        
        for (const [dx, dy, step] of dirs) {
          const nx = cx + dx;
          const ny = cy + dy;
          
          if (nx >= 0 && nx < cols && ny >= 0 && ny < rows) {
            const nIdx = ny * cols + nx;
            if (dist[curr] + step < dist[nIdx]) {
              dist[nIdx] = dist[curr] + step;
              queue.push(nIdx);
            }
          }
        }
      }
      
      // 3. Compute Gradients (Flow Field)
      // For each text cell, look at neighbors to find the steepest descent towards empty space
      for (let y = 1; y < rows - 1; y++) {
        for (let x = 1; x < cols - 1; x++) {
          const i = y * cols + x;
          if (isText[i] === 1) {
            // Central difference to get gradient of the distance field
            const dx = (dist[y * cols + (x - 1)] - dist[y * cols + (x + 1)]) / 2;
            const dy = (dist[(y - 1) * cols + x] - dist[(y + 1) * cols + x]) / 2;
            
            const mag = Math.sqrt(dx * dx + dy * dy);
            if (mag > 0.001) {
              grid[i * 2] = dx / mag;
              grid[i * 2 + 1] = dy / mag;
            }
          }
        }
      }

      setFlowField({
        width: w,
        height: h,
        cellSize,
        getForce: (x: number, y: number) => {
          const cx = Math.floor(x / cellSize);
          const cy = Math.floor(y / cellSize);
          if (cx >= 0 && cx < cols && cy >= 0 && cy < rows) {
            const i = (cy * cols + cx) * 2;
            return { dx: grid[i], dy: grid[i + 1] };
          }
          return { dx: 0, dy: 0 };
        }
      });
    };

    // Wait for SplitText layout
    timeoutId = window.setTimeout(generate, 800);

    const handleResize = () => {
      clearTimeout(timeoutId);
      timeoutId = window.setTimeout(generate, 300);
    };

    window.addEventListener('resize', handleResize);
    return () => {
      clearTimeout(timeoutId);
      window.removeEventListener('resize', handleResize);
    };
  }, [textRef, cellSize]);

  return flowField;
}
